# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    toile_dir: '%kernel.project_dir%/public/photos/decoMurale/toile'
    mdf_dir: '%kernel.project_dir%/public/photos/decoMurale/mdf'
    cadre_dir: '%kernel.project_dir%/public/photos/decoMurale/cadre'
    textile_dir: '%kernel.project_dir%/public/photos/cadeau/textile'
    mugs_dir: '%kernel.project_dir%/public/photos/cadeau/mugs'
    tasseMagique_dir: '%kernel.project_dir%/public/photos/cadeau/tasseMagique'
    tiragePhoto_dir: '%kernel.project_dir%/public/uploads/tirage'
    agrandissement_dir: '%kernel.project_dir%/public/photos/Agrandissement'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

        